# Site settings
author: Biagio Mendolia
title: Software Engineering
header-img: img/home-bg.png
email: mendolia2328@gmail.com
copyright_name: Biagio Mendolia
description: > # this means to ignore newlines until "baseurl:"
  My journey learning web development at Flatiron
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  biagioo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
